### ISSUE TITLE
Does this tool mostly not work on mobile ( iPhone )? 

### ISSUE THREAD

**Issue by halukkaramete** [sjwilliams/scrollstory#36]

**Comment by halukkaramete** [comment]
I've tested all test/demo links on the mobile ( iPhone, such as the NYTimes or the pudding.cool examples  ) but pretty much nothing works except the example ( your own documentation example ) where the header navigation links properly update, per scroll position. I'm perplexed and extremely surprised that such as a fantastic tool has no support for mobile and there is no mention of it. 
Or perhaps, I'm completely missing something somewhere.

**Comment by sjwilliams** [comment]
hi @halukkaramete. ScrollStory should work on any device that dispatches scroll events, including iPhone. I just checked the first two nytimes.com examples from the README on my iPhone 8 and everything worked as expected. For some reason none of the pudding.cool examples worked for me on my iPhone, including the other scrolling tools. I think they have a template bug or something. I'm going to close. If you're using ScrollStory and can send a reproducible bug, I'm happy to reopen and take a look.
